# Generated by Django 3.2.8 on 2024-02-20 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2024, 2, 20, 2, 29, 28, 525894))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2024, 2, 20, 2, 29, 28, 525894))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
    ]
